apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: tinyantu/config-service:latest
        ports:
        - containerPort: 8081  # Puerto interno del contenedor (opcional)
        env:
        - name: SERVER_PORT
          value: "8081"  # Puerto aleatorio
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
  - port: 80  # Puerto expuesto dentro del cluster
    targetPort: 8081
  type: ClusterIP
