apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: tinyantu/eureka-service:latest
        ports:
        - containerPort: 8761   # Puerto interno del contenedor (opcional)
        env:
        - name: SERVER_PORT
          value: "8761 "  # Puerto aleatorio
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
  - port: 80  # Puerto expuesto dentro del cluster
    targetPort: 8761
  type: ClusterIP
