apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30500  # Puerto accesible desde fuera del clúster
