apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: tinyantu/gateway-service:latest
          ports:
            - containerPort: 8081  
          env:
              - name: SPRING_CLOUD_CONFIG_URI # Nombre de la variable de entorno
                value: http://config-service:8081
              - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE # Nombre de la variable de entorno
                value: http://eureka-service:8761
              - name: eureka.instance.preferIpAddress
                value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080  # Puerto expuesto dentro del cluster
      targetPort: 8080  # Puerto del contenedor
  type: LoadBalancer
