apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-credentials
              key: password
        - name: POSTGRES_DB_Simulate
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB_Simulate
        - name: POSTGRES_DB_Register
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB_Register
        - name: POSTGRES_DB_Request
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB_Request
        - name: POSTGRES_DB_Evaluate
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB_Evaluate
        - name: POSTGRES_DB_Follow
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB_Follow
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi  # Al menos 1 GiB recomendado
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
