server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':  # Aplica a todas las rutas del Gateway
            allowedOrigins:
              - "http://localhost:5173" # Reemplaza con la URL del frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS  # Necesario para preflight requests
            allowedHeaders:
              - "*"  # Permitir todos los encabezados
            allowCredentials: true  # Permitir envío de cookies o tokens
            maxAge: 3600  # Cacheo de la configuración CORS

      discovery:
        locator:
          enabled: true
      routes:
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/register/**
        - id: requestCredit-service
          uri: lb://requestCredit-service
          predicates:
            - Path=/requestCredit/**
        - id: evaluateCredit-service
          uri: lb://evaluateCredit-service
          predicates:
            - Path=/evaluateCredit/**
        - id: followCredit-service
          uri: lb://followCredit-service
          predicates:
            - Path=/followCredit/**
